# =============================================================================
# Prometheus Configuration for DRP
# =============================================================================
# This configuration monitors DRP nodes and services

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # =============================================================================
  # Main DRP Node
  # =============================================================================
  - job_name: 'drp-main-node'
    static_configs:
      - targets: ['drp-node:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # =============================================================================
  # Validator Nodes
  # =============================================================================
  - job_name: 'drp-validator-1'
    static_configs:
      - targets: ['drp-validator-1:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'drp-validator-2'
    static_configs:
      - targets: ['drp-validator-2:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # =============================================================================
  # AI Elder Service
  # =============================================================================
  - job_name: 'drp-ai-elder'
    static_configs:
      - targets: ['drp-ai-elder:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # =============================================================================
  # Prometheus Self-Monitoring
  # =============================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # =============================================================================
  # Docker Containers
  # =============================================================================
  - job_name: 'docker-containers'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # =============================================================================
  # Node Exporter (if available)
  # =============================================================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

