# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdrp.proto\x12\x03\x64rp\"\x83\x01\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x11\n\tsignature\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x10\n\x08metadata\x18\x07 \x01(\t\"\xaa\x01\n\x05\x42lock\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x15\n\rprevious_hash\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12&\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x10.drp.Transaction\x12\r\n\x05miner\x18\x06 \x01(\t\x12\r\n\x05nonce\x18\x07 \x01(\x03\x12\x14\n\x0cstatus_proof\x18\x08 \x01(\t\"?\n\tHeartbeat\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0e\n\x06status\x18\x03 \x01(\t\"b\n\x13VerificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\ractivity_type\x18\x02 \x01(\t\x12\x11\n\tmedia_url\x18\x03 \x01(\t\x12\x10\n\x08metadata\x18\x04 \x01(\t\"5\n\x14VerificationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd8\x01\n\x07\x44rpNode\x12\x32\n\x14\x42roadcastTransaction\x12\x10.drp.Transaction\x1a\x08.drp.Ack\x12#\n\x0bSubmitBlock\x12\n.drp.Block\x1a\x08.drp.Ack\x12 \n\x04Ping\x12\x0e.drp.Heartbeat\x1a\x08.drp.Ack\x12R\n\x1bRequestActivityVerification\x12\x18.drp.VerificationRequest\x1a\x19.drp.VerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=19
  _globals['_TRANSACTION']._serialized_end=150
  _globals['_BLOCK']._serialized_start=153
  _globals['_BLOCK']._serialized_end=323
  _globals['_HEARTBEAT']._serialized_start=325
  _globals['_HEARTBEAT']._serialized_end=388
  _globals['_VERIFICATIONREQUEST']._serialized_start=390
  _globals['_VERIFICATIONREQUEST']._serialized_end=488
  _globals['_VERIFICATIONRESPONSE']._serialized_start=490
  _globals['_VERIFICATIONRESPONSE']._serialized_end=543
  _globals['_ACK']._serialized_start=545
  _globals['_ACK']._serialized_end=584
  _globals['_DRPNODE']._serialized_start=587
  _globals['_DRPNODE']._serialized_end=803
# @@protoc_insertion_point(module_scope)
