# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import drp_pb2 as drp__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in drp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DrpNodeStub(object):
    """DRP Node Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastTransaction = channel.unary_unary(
                '/drp.DrpNode/BroadcastTransaction',
                request_serializer=drp__pb2.Transaction.SerializeToString,
                response_deserializer=drp__pb2.Ack.FromString,
                _registered_method=True)
        self.SubmitBlock = channel.unary_unary(
                '/drp.DrpNode/SubmitBlock',
                request_serializer=drp__pb2.Block.SerializeToString,
                response_deserializer=drp__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/drp.DrpNode/Ping',
                request_serializer=drp__pb2.Heartbeat.SerializeToString,
                response_deserializer=drp__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestActivityVerification = channel.unary_unary(
                '/drp.DrpNode/RequestActivityVerification',
                request_serializer=drp__pb2.VerificationRequest.SerializeToString,
                response_deserializer=drp__pb2.VerificationResponse.FromString,
                _registered_method=True)


class DrpNodeServicer(object):
    """DRP Node Service
    """

    def BroadcastTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestActivityVerification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DrpNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastTransaction,
                    request_deserializer=drp__pb2.Transaction.FromString,
                    response_serializer=drp__pb2.Ack.SerializeToString,
            ),
            'SubmitBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBlock,
                    request_deserializer=drp__pb2.Block.FromString,
                    response_serializer=drp__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=drp__pb2.Heartbeat.FromString,
                    response_serializer=drp__pb2.Ack.SerializeToString,
            ),
            'RequestActivityVerification': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestActivityVerification,
                    request_deserializer=drp__pb2.VerificationRequest.FromString,
                    response_serializer=drp__pb2.VerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drp.DrpNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drp.DrpNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DrpNode(object):
    """DRP Node Service
    """

    @staticmethod
    def BroadcastTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drp.DrpNode/BroadcastTransaction',
            drp__pb2.Transaction.SerializeToString,
            drp__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drp.DrpNode/SubmitBlock',
            drp__pb2.Block.SerializeToString,
            drp__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drp.DrpNode/Ping',
            drp__pb2.Heartbeat.SerializeToString,
            drp__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestActivityVerification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drp.DrpNode/RequestActivityVerification',
            drp__pb2.VerificationRequest.SerializeToString,
            drp__pb2.VerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
